### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by rayegun** [JuliaSparse/CIndices.jl#1]
@willow-ahrens can I release this and perhaps Finch depend? It's very clunky otherwise (I'd like Finch.jl to be an extension package to my packages right now, so I can't depend on Finch for it. But I'd like this in a variety of places!)

**Comment by willow-ahrens** [comment]
Sure, could you add me to the repo? I'd like to copy over the docs from Finch as well before we release.

**Comment by rayegun** [comment]
Added to JuliaSparse as owner, should be enough?

**Comment by willow-ahrens** [comment]
Yep! Gonna get some coffee and copy over. Do you have any SparseMatrixCSC or SparseVector use cases with CIndex we could add to the tests?

**Comment by rayegun** [comment]
Hmm, I know you can construct one and do stuff with it (bcasting, multiplication, etc). I'm mostly trying to use it to set up solvers right now, but I think just some basic tests with SparseMatrixCSC should be fine.

As a test dep only though. I can do that in a bit.

**Comment by willow-ahrens** [comment]
Ok! I'm now happy to add CIndex as a Finch.jl dep as soon as it's released.
